### ISSUE TITLE
Shop page layout feels unbalanced

### ISSUE THREAD

**Issue by rlmckenney** [rlmckenney/mtm6330-midterm-mckennr#10]
Main content in section blh blh blh feels w=too heavily weighted to one side.

```css
.some-class {
  background: $primary;
}
```
